
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 04161113005
 */
public class Principal extends javax.swing.JFrame {
 private final  JDesktopPane desktop = new JDesktopPane();
 
 protected void createFrame(){
     final cadastrodeproduto  frame = new cadastrodeproduto();
     frame.setVisible(true);
     desktop.add(frame);
     try{
         frame.setSelected(true);
         frame.setEnabled(true);
     }catch( final PropertyVetoException e){
         
     }
 }
    public Principal() {
        initComponents();
        
        final int inset = 50;
        final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        final Dimension dimension = new Dimension(screenSize.width, screenSize.height);
        this.setBounds(inset, inset, dimension.width - inset * 2, dimension.height - inset *2); 
         
         this.setContentPane(desktop);
         desktop.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        produto = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenuItem();
        vendas = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        rproduto = new javax.swing.JMenuItem();
        rcliente = new javax.swing.JMenuItem();
        rvenda = new javax.swing.JMenuItem();
        opcoes = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastro.setText("Cadastro");

        produto.setText("Produtos");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        cadastro.add(produto);

        cliente.setText("Clientes");
        cadastro.add(cliente);

        vendas.setText("Vendas");
        cadastro.add(vendas);

        barra.add(cadastro);

        relatorio.setText("Relatórios");

        rproduto.setText("Relatório dos Produtos");
        rproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprodutoActionPerformed(evt);
            }
        });
        relatorio.add(rproduto);

        rcliente.setText("Relatório dos Clientes");
        relatorio.add(rcliente);

        rvenda.setText("Relatório de Vendas");
        rvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvendaActionPerformed(evt);
            }
        });
        relatorio.add(rvenda);

        barra.add(relatorio);

        opcoes.setText("Opções");

        sair.setText("Sair do Sistema");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        opcoes.add(sair);

        barra.add(opcoes);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        createFrame();
    }//GEN-LAST:event_produtoActionPerformed

    private void rprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rprodutoActionPerformed

    private void rvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rvendaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenu opcoes;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem rcliente;
    private javax.swing.JMenu relatorio;
    private javax.swing.JMenuItem rproduto;
    private javax.swing.JMenuItem rvenda;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem vendas;
    // End of variables declaration//GEN-END:variables
}
